services:
  angular:
    build: ./angular-project
    volumes:
      - ./nodejs-express-project/dist:/app/dist

  express:
    build: ./nodejs-express-project
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: on-failure
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
