services:
  app:
    build: .
    ports:
      - 80:80
    restart: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: on-failure
    volumes:
      - ./data:/data/db
